import { redirect } from "next/navigation";
import { headers } from "next/headers";
import { auth } from "@/lib/auth";
import { SiteShell, PageHero } from "@/components/site-shell";
import { db } from "@/lib/db";
import { studentRequest } from "@/lib/db/schema";
import { desc, eq } from "drizzle-orm";

export default async function StudentDashboardPage() { const session = await auth.api.getSession({ headers: await headers() }); if (!session?.user) redirect("/sign-in?next=/student/dashboard"); const requests = await db.select().from(studentRequest).where(eq(studentRequest.userId, session.user.id)).orderBy(desc(studentRequest.createdAt)); return <SiteShell><PageHero eyebrow="Student dashboard" title={`Welcome back, ${session.user.name}.`} intro="Track your project requests, understand next steps, and keep your academic work aligned with your own learning." /><main className="section"><div className="container student-dashboard-grid"><article className="admin-form-card"><p className="card-kicker">My requests</p>{requests.length ? <div className="admin-list">{requests.map((request) => <div className="admin-inquiry" key={request.id}><div><strong>{request.projectTitle}</strong><p>{request.referenceId} · {request.projectType}</p></div><span>{request.status}</span></div>)}</div> : <><h2>No requests yet</h2><p>Start with a clear project brief and receive a private reference ID.</p></>}<a className="button button-primary" href="/student/request">Request a project →</a></article><article className="admin-form-card"><p className="card-kicker">Academic support</p><h2>Build understanding.</h2><p>Use explanation and viva coaching to prepare your own submission. We do not complete assessed work on your behalf.</p><a className="text-link" href="/student/request">Ask about coaching →</a></article></div></main></SiteShell>; }
