import { and, desc, eq } from "drizzle-orm";
import { headers } from "next/headers";
import { auth } from "@/lib/auth";
import { db } from "@/lib/db";
import { companyStatistics, projectUpdateRequest, statisticsAuditLog, user, notification } from "@/lib/db/schema";

export const PUBLIC_STATS = { totalQueries: 347, completedProjects: 149, liveProjects: 6 };

type Role = "employee" | "manager" | "owner" | "admin";
async function member() { const session = await auth.api.getSession({ headers: await headers() }); if (!session?.user) throw new Error("Unauthorized"); return session.user as typeof session.user & { role?: Role }; }
async function requireTeam() { const current = await member(); if (!["employee", "manager", "owner", "admin"].includes(current.role ?? "")) throw new Error("Forbidden"); return current; }
async function ensureStats() { const existing = await db.select().from(companyStatistics).where(eq(companyStatistics.id, "company")).limit(1); if (existing[0]) return existing[0]; const [created] = await db.insert(companyStatistics).values({ id: "company" }).returning(); return created; }
export async function getPublicStatistics() { const stats = await ensureStats(); return { totalQueries: stats.publicQueryCount, completedProjects: stats.publicCompletedProjects, liveProjects: stats.publicLiveProjects }; }
export async function getCompanyStatistics() { await requireTeam(); const stats = await ensureStats(); const requests = await db.select().from(projectUpdateRequest).orderBy(desc(projectUpdateRequest.createdAt)).limit(20); const audit = await db.select().from(statisticsAuditLog).orderBy(desc(statisticsAuditLog.createdAt)).limit(20); return { stats, requests, audit }; }
export async function createProjectUpdate(type: "completed_project" | "live_project" | "complete_live_project", projectName?: string, description?: string) { const current = await requireTeam(); if (projectName && projectName.length > 160) throw new Error("Project name is too long."); const [request] = await db.insert(projectUpdateRequest).values({ id: crypto.randomUUID(), type, projectName: projectName?.trim() || null, description: description?.trim() || null, requestedBy: current.id }).returning(); const reviewers = await db.select({ id: user.id }).from(user).where(and(eq(user.role, "manager"), eq(user.role, "manager"))); const owners = await db.select({ id: user.id }).from(user).where(eq(user.role, "owner")); await Promise.all([...reviewers, ...owners].map((reviewer) => db.insert(notification).values({ id: crypto.randomUUID(), userId: reviewer.id, title: "Statistics approval requested", body: `${type.replaceAll("_", " ")} needs your review.`, href: "/team" }))); return request; }
export async function reviewProjectUpdate(id: string, decision: "approved" | "rejected", rejectionReason?: string) { const reviewer = await requireTeam(); if (reviewer.role !== "manager" && reviewer.role !== "owner" && reviewer.role !== "admin") throw new Error("Forbidden"); const request = (await db.select().from(projectUpdateRequest).where(eq(projectUpdateRequest.id, id)).limit(1))[0]; if (!request || request.status === "approved" || request.status === "rejected") throw new Error("Request is no longer reviewable."); const isManager = reviewer.role === "manager"; const managerApproval = isManager ? decision : request.managerApproval; const ownerApproval = !isManager ? decision : request.ownerApproval; if (decision === "rejected") { await db.update(projectUpdateRequest).set({ status: "rejected", managerApproval, ownerApproval, rejectionReason: rejectionReason?.trim() || "Rejected by reviewer" }).where(eq(projectUpdateRequest.id, id)); return; } const approved = managerApproval === "approved" && ownerApproval === "approved"; await db.update(projectUpdateRequest).set({ status: approved ? "approved" : isManager ? "pending_owner" : "pending_manager", managerApproval, ownerApproval, ...(isManager ? { managerApprovedAt: new Date() } : { ownerApprovedAt: new Date() }) }).where(eq(projectUpdateRequest.id, id)); if (!approved) return; const stats = await ensureStats(); const delta = request.type === "complete_live_project" ? { completed: 1, live: -1 } : request.type === "completed_project" ? { completed: 1, live: 0 } : { completed: 0, live: 1 }; await db.update(companyStatistics).set({ internalCompletedProjects: stats.internalCompletedProjects + delta.completed, internalLiveProjects: stats.internalLiveProjects + delta.live, publicCompletedProjects: stats.publicCompletedProjects + delta.completed, publicLiveProjects: stats.publicLiveProjects + delta.live, updatedAt: new Date() }).where(eq(companyStatistics.id, "company")); await db.insert(statisticsAuditLog).values({ id: crypto.randomUUID(), action: request.type, userId: request.requestedBy, previousValue: request.type === "live_project" ? stats.internalLiveProjects : stats.internalCompletedProjects, newValue: request.type === "live_project" ? stats.internalLiveProjects + 1 : stats.internalCompletedProjects + 1, approvalStatus: "approved", managerApproval, ownerApproval, relatedRequestId: id }); }

export async function recordSuccessfulInquiry(inquiryId: string) { const stats = await ensureStats(); await db.update(companyStatistics).set({ internalQueryCount: stats.internalQueryCount + 1, publicQueryCount: stats.publicQueryCount + 1, updatedAt: new Date() }).where(eq(companyStatistics.id, "company")); return inquiryId; }
